### ISSUE TITLE
Show a better message when a mapping is missing

### ISSUE THREAD

**Issue by clemensp** [nulogy/vorpal#7]
Currently, if I define a mapping that contains a has_many:

```
        map Parent, table_name: "parents" do
          has_many :children, owned: true, child_class: Child, fk: 'child_id'
        end
```

But don't define the mapping for Child, I get the following error:

```
<ruby_directory>/gems/vorpal-0.0.7/lib/vorpal/configs.rb:46:in `block in initialize_association_configs': undefined method `local_association_configs' for nil:NilClass (NoMethodError)
    from <ruby_directory>/gems/vorpal-0.0.7/lib/vorpal/configs.rb:45:in `each'
    from <ruby_directory>/gems/vorpal-0.0.7/lib/vorpal/configs.rb:45:in `initialize_association_configs'
    from <ruby_directory>/gems/vorpal-0.0.7/lib/vorpal/configs.rb:9:in `initialize'
    from <ruby_directory>/gems/vorpal-0.0.7/lib/vorpal/configuration.rb:50:in `new'
    from <ruby_directory>/gems/vorpal-0.0.7/lib/vorpal/configuration.rb:50:in `build_config'
    from <ruby_directory>/gems/vorpal-0.0.7/lib/vorpal/configuration.rb:15:in `define'
    from <vorpal mapping file>:8:in `instance'
```

The error message should help me diagnose the problem, indicating that the mapping for Child is missing.

**Comment by clemensp** [comment]
Thanks!
